# Generated by Django 5.1.1 on 2024-10-05 10:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)])),
                ('company_name', models.CharField(max_length=511, unique=True)),
                ('company_building_name', models.CharField(max_length=255)),
                ('company_floor', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2)])),
                ('company_parking_place_number', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(default=0, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)])),
                ('employee_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('shift', models.CharField(max_length=127)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.company')),
            ],
        ),
    ]
