# Generated by Django 5.1.1 on 2024-10-07 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_employee_email_remove_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employee.company'),
        ),
    ]
